### ISSUE TITLE
Failure: Unsatisfied version range 

### ISSUE THREAD

**Issue by vidhuamit0606** [changhuixu/uiowa-header-demo#3]
issue when trying to install core-js , projects package plz suggesr @changhuixu 
![image](https://user-images.githubusercontent.com/9607899/148034742-2081578b-af3f-43c4-bf31-f27ade20f2ac.png)

**Comment by changhuixu** [comment]
Hi @vidhuamit0606 ,
I think it's a problem on the StackBlitz end. You can verify it by checking the `package.json` file. The versions don't match what in the `main` branch.

**Comment by vidhuamit0606** [comment]
Sure @changhuixu , would take this help
